import java.awt.event.*;
import java.sql.*;
import javax.swing.*; 
import java.awt.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ben
 */
public class partone extends javax.swing.JFrame {

    /**
     * Creates new form partone
     */
    public partone() {
        initComponents();
        lbl_emp.setText(String.valueOf(Emp.empid).toString());
    }
      public void close(){
        WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbl_emp = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        allowance_btn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel4.setForeground(new java.awt.Color(252, 245, 245));
        jLabel4.setText("Logged in as : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 500, 150, 17);

        lbl_emp.setText("User");
        jPanel1.add(lbl_emp);
        lbl_emp.setBounds(130, 500, 60, 17);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_Calculator_track.png"))); // NOI18N
        jButton1.setText("Gratuity Stand");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 190, 170, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Manager-Suit-Red-Tie-Rose-icon.png"))); // NOI18N
        jButton2.setText("Employee Manager");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 120, 190, 50);

        allowance_btn.setIcon(new javax.swing.ImageIcon("/home/ben/NetBeansProjects/projectone/src/images/Manager-Suit-Red-Tie-Rose-icon.png")); // NOI18N
        allowance_btn.setText("Report Generation");
        allowance_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allowance_btnActionPerformed(evt);
            }
        });
        jPanel1.add(allowance_btn);
        allowance_btn.setBounds(10, 190, 190, 50);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/comment-edit-icon.png"))); // NOI18N
        jButton6.setText("Admin Manager");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(240, 120, 170, 50);

        jButton3.setText("Help Button");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(120, 250, 190, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apps-session-logout-icon.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(550, 20, 40, 20);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(251, 241, 241));
        jLabel3.setText("ADMINISTRATION SECTION");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 0, 500, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMG-20160919-WA0014.jpg"))); // NOI18N
        jLabel1.setText("enter");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 650, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       close();
        EmployeeInfo empinf = new EmployeeInfo();
        empinf.setVisible(true);
       
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         close();
        gratuitystand gst = new  gratuitystand();
        gst.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void allowance_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allowance_btnActionPerformed
        // TODO add your handling code here:
        close();
                gratuitystand gt = new gratuitystand();
                 gt.setVisible(true);
                 
   close();
        gratuitystand gst = new  gratuitystand();
        gst.setVisible(true);
    }//GEN-LAST:event_allowance_btnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "You are part of the administrators thanks for using GRBS");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

      JOptionPane.showMessageDialog(null, "Do you really want to exit");
        close();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            JOptionPane.showMessageDialog(null, "This is the gratuity and retirement benefit system help section."
                    + "you are welcome to GRBS"+"when you try to open a button and the system freezes please refresh the system will work properrly");
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(partone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(partone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(partone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(partone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new partone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allowance_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_emp;
    // End of variables declaration//GEN-END:variables
}
